--
-- Dummy data for oracle_hosts (20 rows) and mssql_hosts (50 rows)
--
delete from oracle_hosts;
delete from mssql_hosts;

-- ============================================================
-- oracle_hosts
-- ============================================================
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-prod-01',
           32,
           256,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-prod-02',
           32,
           256,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-prod-03',
           64,
           512,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-exacc-01',
           96,
           768,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-exacc-02',
           96,
           768,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PROD',
           'Standard Edition 2',
           'oradb-se2-prod-01',
           8,
           64,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PROD',
           'Standard Edition 2',
           'oradb-se2-prod-02',
           8,
           64,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-aix-01',
           16,
           128,
           'SLES 16' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-aix-02',
           16,
           128,
           'SLES 16' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'UAT',
           'Enterprise Edition',
           'oradb-uat-01',
           16,
           128,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'UAT',
           'Enterprise Edition',
           'oradb-uat-02',
           8,
           64,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'UAT',
           'Standard Edition 2',
           'oradb-se2-uat-01',
           4,
           32,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'DEV',
           'Enterprise Edition',
           'oradb-dev-01',
           8,
           64,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'DEV',
           'Enterprise Edition',
           'oradb-dev-02',
           8,
           64,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'DEV',
           'Standard Edition 2',
           'oradb-se2-dev-01',
           4,
           32,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'DEV',
           'Standard Edition 2',
           'oradb-se2-dev-02',
           4,
           16,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'QA',
           'Enterprise Edition',
           'oradb-qa-01',
           8,
           64,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'QA',
           'Standard Edition 2',
           'oradb-se2-qa-01',
           4,
           32,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PREPROD',
           'Enterprise Edition',
           'oradb-pprod-01',
           16,
           128,
           'Linux x86 64-bit' );
insert into oracle_hosts (
   environment,
   license_type,
   hostname,
   num_cpus,
   memory_gb,
   os_type
) values ( 'PREPROD',
           'Enterprise Edition',
           'oradb-pprod-02',
           16,
           128,
           'SLES 15 sp7' );

-- ============================================================
-- mssql_hosts
-- ============================================================
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPROD01',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLPROD01',
           null,
           null,
           25,
           4,
           0,
           32768,
           0,
           16,
           64,
           'Windows 2019',
           'CORP\sqlsvc_prod',
           'PROD',
           'CORE',
           20190315 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPROD02',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLPROD02',
           null,
           null,
           25,
           4,
           0,
           32768,
           0,
           16,
           64,
           'Windows 2019',
           'CORP\sqlsvc_prod',
           'PROD',
           'CORE',
           20190315 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPROD03',
           'Enterprise Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLPROD03',
           null,
           null,
           50,
           8,
           0,
           65536,
           0,
           32,
           128,
           'Windows 2022',
           'CORP\sqlsvc_prod',
           'PROD',
           'CORE',
           20230601 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPROD04',
           'Enterprise Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLPROD04',
           null,
           null,
           50,
           8,
           0,
           65536,
           0,
           32,
           128,
           'Windows 2022',
           'CORP\sqlsvc_prod',
           'PROD',
           'CORE',
           20230601 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPROD05',
           'Enterprise Edition (64-bit)',
           '14.0.3460.9',
           'SQL_Latin1_General_CP1_CI_AS',
           0,
           'SQLPROD05',
           null,
           null,
           5,
           2,
           0,
           16384,
           0,
           8,
           32,
           'Windows 2016',
           'NT Service\MSSQLSERVER',
           'PROD',
           'CORE',
           20170820 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLCLU01',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           1,
           'SQLCLU01N1',
           'SQLCLU01N1',
           'SQLCLU01N2',
           25,
           4,
           0,
           49152,
           0,
           16,
           128,
           'Windows 2019',
           'CORP\sqlsvc_clu',
           'PROD',
           'CORE',
           20200910 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLCLU02',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           1,
           'SQLCLU02N1',
           'SQLCLU02N1',
           'SQLCLU02N2',
           25,
           4,
           0,
           49152,
           0,
           16,
           128,
           'Windows 2019',
           'CORP\sqlsvc_clu',
           'PROD',
           'CORE',
           20200910 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLCLU03',
           'Enterprise Edition (64-bit)',
           '16.0.4165.4',
           'Latin1_General_CI_AS',
           1,
           'SQLCLU03N1',
           'SQLCLU03N1',
           'SQLCLU03N2',
           50,
           8,
           0,
           98304,
           0,
           32,
           256,
           'Windows 2022',
           'CORP\sqlsvc_clu',
           'PROD',
           'CORE',
           20231115 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLSTD01',
           'Standard Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLSTD01',
           null,
           null,
           5,
           0,
           0,
           8192,
           0,
           4,
           16,
           'Windows 2019',
           'NT Service\MSSQLSERVER',
           'PROD',
           'CAL',
           20210303 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLSTD02',
           'Standard Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLSTD02',
           null,
           null,
           5,
           0,
           0,
           8192,
           0,
           4,
           16,
           'Windows 2019',
           'NT Service\MSSQLSERVER',
           'PROD',
           'CAL',
           20210303 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLSTD03',
           'Standard Edition (64-bit)',
           '14.0.3460.9',
           'French_CI_AS',
           0,
           'SQLSTD03',
           null,
           null,
           5,
           0,
           0,
           4096,
           1,
           4,
           8,
           'Windows 2016',
           'NT Service\MSSQLSERVER',
           'PROD',
           'CAL',
           20180615 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLSTD04',
           'Standard Edition (64-bit)',
           '16.0.4165.4',
           'Latin1_General_CI_AS',
           0,
           'SQLSTD04',
           null,
           null,
           5,
           2,
           0,
           8192,
           0,
           8,
           32,
           'Windows 2022',
           'CORP\sqlsvc_std',
           'PROD',
           'CORE',
           20240101 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLSTD05',
           'Standard Edition (64-bit)',
           '16.0.4165.4',
           'Latin1_General_CI_AS',
           0,
           'SQLSTD05',
           null,
           null,
           5,
           2,
           0,
           8192,
           0,
           8,
           32,
           'Windows 2022',
           'CORP\sqlsvc_std',
           'PROD',
           'CORE',
           20240115 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPPROD01',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLPPROD01',
           null,
           null,
           25,
           4,
           0,
           32768,
           0,
           16,
           64,
           'Windows 2019',
           'CORP\sqlsvc_prod',
           'PREPROD',
           'CORE',
           20191010 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPPROD02',
           'Standard Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLPPROD02',
           null,
           null,
           5,
           2,
           0,
           16384,
           0,
           8,
           32,
           'Windows 2019',
           'CORP\sqlsvc_uat',
           'PREPROD',
           'CORE',
           20191010 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLUAT01',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLUAT01',
           null,
           null,
           25,
           4,
           0,
           16384,
           0,
           8,
           32,
           'Windows 2019',
           'CORP\sqlsvc_uat',
           'UAT',
           'CORE',
           20200120 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLUAT02',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLUAT02',
           null,
           null,
           25,
           4,
           0,
           16384,
           0,
           8,
           32,
           'Windows 2019',
           'CORP\sqlsvc_uat',
           'UAT',
           'CORE',
           20200120 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLUAT03',
           'Standard Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLUAT03',
           null,
           null,
           5,
           2,
           0,
           8192,
           0,
           4,
           16,
           'Windows 2022',
           'CORP\sqlsvc_uat',
           'UAT',
           'CAL',
           20230901 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLUAT04',
           'Standard Edition (64-bit)',
           '14.0.3460.9',
           'SQL_Latin1_General_CP1_CI_AS',
           0,
           'SQLUAT04',
           null,
           null,
           5,
           0,
           0,
           4096,
           0,
           4,
           8,
           'Windows 2016',
           'NT Service\MSSQLSERVER',
           'UAT',
           'CAL',
           20170501 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLUAT05',
           'Standard Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLUAT05',
           null,
           null,
           5,
           2,
           0,
           8192,
           0,
           4,
           16,
           'Windows 2022',
           'CORP\sqlsvc_uat',
           'UAT',
           'CAL',
           20240301 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDEV01',
           'Developer Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLDEV01',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           4,
           16,
           'Windows 2022',
           'NT Service\MSSQLSERVER',
           'DEV',
           'DEVELOPER',
           20230215 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDEV02',
           'Developer Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLDEV02',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           4,
           16,
           'Windows 2022',
           'NT Service\MSSQLSERVER',
           'DEV',
           'DEVELOPER',
           20230215 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDEV03',
           'Developer Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLDEV03',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           1,
           4,
           8,
           'Windows 2019',
           'NT Service\MSSQLSERVER',
           'DEV',
           'DEVELOPER',
           20210701 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDEV04',
           'Developer Edition (64-bit)',
           '15.0.4385.2',
           'SQL_Latin1_General_CP1_CI_AS',
           0,
           'SQLDEV04',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           8,
           16,
           'Windows 2019',
           'NT Service\MSSQLSERVER',
           'DEV',
           'DEVELOPER',
           20220401 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDEV05',
           'Developer Edition (64-bit)',
           '14.0.3460.9',
           'French_CI_AS',
           0,
           'SQLDEV05',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           4,
           8,
           'Windows 2016',
           'NT Service\MSSQLSERVER',
           'DEV',
           'DEVELOPER',
           20180101 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDEV06',
           'Developer Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLDEV06',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           4,
           16,
           'Windows 2022',
           'NT Service\MSSQLSERVER',
           'DEV',
           'DEVELOPER',
           20240601 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDEV07',
           'Developer Edition (64-bit)',
           '16.0.4165.4',
           'Latin1_General_CI_AS',
           0,
           'SQLDEV07',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           4,
           16,
           'Windows 2022',
           'NT Service\MSSQLSERVER',
           'DEV',
           'DEVELOPER',
           20240701 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDEV08',
           'Developer Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLDEV08',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           4,
           8,
           'Windows 2019',
           'NT Service\MSSQLSERVER',
           'DEV',
           'DEVELOPER',
           20211201 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDEV09',
           'Developer Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLDEV09',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           4,
           16,
           'Windows 2022',
           'NT Service\MSSQLSERVER',
           'DEV',
           'DEVELOPER',
           20250102 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDEV10',
           'Developer Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLDEV10',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           8,
           32,
           'Windows 2022',
           'CORP\sqlsvc_dev',
           'DEV',
           'DEVELOPER',
           20250201 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLQA01',
           'Standard Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLQA01',
           null,
           null,
           5,
           2,
           0,
           8192,
           0,
           4,
           16,
           'Windows 2019',
           'NT Service\MSSQLSERVER',
           'QA',
           'CAL',
           20200501 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLQA02',
           'Standard Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLQA02',
           null,
           null,
           5,
           2,
           0,
           8192,
           0,
           4,
           16,
           'Windows 2022',
           'NT Service\MSSQLSERVER',
           'QA',
           'CAL',
           20230701 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLQA03',
           'Standard Edition (64-bit)',
           '14.0.3460.9',
           'SQL_Latin1_General_CP1_CI_AS',
           0,
           'SQLQA03',
           null,
           null,
           5,
           0,
           0,
           4096,
           0,
           4,
           8,
           'Windows 2016',
           'NT Service\MSSQLSERVER',
           'QA',
           'CAL',
           20171105 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLAGPROD01',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLAGPROD01',
           null,
           null,
           25,
           8,
           0,
           49152,
           0,
           16,
           128,
           'Windows 2019',
           'CORP\sqlsvc_ag',
           'PROD',
           'CORE',
           20201201 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLAGPROD02',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLAGPROD02',
           null,
           null,
           25,
           8,
           0,
           49152,
           0,
           16,
           128,
           'Windows 2019',
           'CORP\sqlsvc_ag',
           'PROD',
           'CORE',
           20201201 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLAGPROD03',
           'Enterprise Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLAGPROD03',
           null,
           null,
           25,
           8,
           0,
           65536,
           0,
           32,
           256,
           'Windows 2022',
           'CORP\sqlsvc_ag',
           'PROD',
           'CORE',
           20231001 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLAGPROD04',
           'Enterprise Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLAGPROD04',
           null,
           null,
           25,
           8,
           0,
           65536,
           0,
           32,
           256,
           'Windows 2022',
           'CORP\sqlsvc_ag',
           'PROD',
           'CORE',
           20231001 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLREP01',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLREP01',
           null,
           null,
           5,
           4,
           0,
           32768,
           0,
           16,
           64,
           'Windows 2019',
           'CORP\sqlsvc_rep',
           'PROD',
           'CORE',
           20211001 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLREP02',
           'Enterprise Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLREP02',
           null,
           null,
           5,
           4,
           0,
           32768,
           0,
           16,
           64,
           'Windows 2019',
           'CORP\sqlsvc_rep',
           'PROD',
           'CORE',
           20211001 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLLEGACY01',
           'Standard Edition (64-bit)',
           '13.0.6441.1',
           'SQL_Latin1_General_CP1_CI_AS',
           0,
           'SQLLEGACY01',
           null,
           null,
           5,
           0,
           0,
           4096,
           1,
           4,
           8,
           'Windows 2012 R2',
           'NT Service\MSSQLSERVER',
           'PROD',
           'CAL',
           20160201 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLLEGACY02',
           'Standard Edition (64-bit)',
           '13.0.6441.1',
           'SQL_Latin1_General_CP1_CI_AS',
           0,
           'SQLLEGACY02',
           null,
           null,
           5,
           0,
           0,
           4096,
           1,
           4,
           8,
           'Windows 2012 R2',
           'NT Service\MSSQLSERVER',
           'PROD',
           'CAL',
           20160201 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPROD06',
           'Enterprise Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLPROD06',
           null,
           null,
           50,
           8,
           0,
           65536,
           0,
           32,
           128,
           'Windows 2022',
           'CORP\sqlsvc_prod',
           'PROD',
           'CORE',
           20240901 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPROD07',
           'Enterprise Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLPROD07',
           null,
           null,
           50,
           8,
           0,
           65536,
           0,
           32,
           128,
           'Windows 2022',
           'CORP\sqlsvc_prod',
           'PROD',
           'CORE',
           20241001 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPROD08',
           'Standard Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLPROD08',
           null,
           null,
           5,
           2,
           0,
           16384,
           0,
           8,
           32,
           'Windows 2019',
           'CORP\sqlsvc_prod',
           'PROD',
           'CORE',
           20220101 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLPROD09',
           'Standard Edition (64-bit)',
           '16.0.4165.4',
           'Latin1_General_CI_AS',
           0,
           'SQLPROD09',
           null,
           null,
           5,
           2,
           0,
           16384,
           0,
           8,
           32,
           'Windows 2022',
           'CORP\sqlsvc_prod',
           'PROD',
           'CORE',
           20241115 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDMUAT01',
           'Developer Edition (64-bit)',
           '16.0.4165.4',
           'French_CI_AS',
           0,
           'SQLDMUAT01',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           4,
           16,
           'Windows 2022',
           'NT Service\MSSQLSERVER',
           'UAT',
           'DEVELOPER',
           20250101 );
insert into mssql_hosts (
   hostname,
   mssql_edition,
   mssql_product_version,
   collation,
   is_clustered,
   activenodename,
   clusternode1,
   clusternode2,
   parallel_threshold,
   max_dop,
   min_memory,
   max_memory,
   xp_cmdshell_enabled,
   num_cpus,
   memory_gb,
   os_type,
   service_account,
   env,
   license_type,
   install_date
) values ( 'SQLDMQA01',
           'Developer Edition (64-bit)',
           '15.0.4385.2',
           'French_CI_AS',
           0,
           'SQLDMQA01',
           null,
           null,
           5,
           0,
           0,
           2147483647,
           0,
           4,
           8,
           'Windows 2019',
           'NT Service\MSSQLSERVER',
           'QA',
           'DEVELOPER',
           20211115 );

-- ============================================================
-- oracle_databases
-- ============================================================
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-prod-01',
           'CDBPROD1',
           '19.22.0.0.0',
           'CDBPROD',
           'ARCHIVELOG',
           'PRIMARY',
           'CDBPROD',
           'AL32UTF8',
           'Enterprise Edition',
           'YES',
           '32768 MB',
           '8192 MB',
           '1200 GB',
           '2000 GB',
           'oradb-prod-01:1521/CDBPROD',
           'CDB',
           3 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-prod-02',
           'CDBPROD2',
           '19.22.0.0.0',
           'CDBPROD',
           'ARCHIVELOG',
           'PRIMARY',
           'CDBPROD',
           'AL32UTF8',
           'Enterprise Edition',
           'YES',
           '32768 MB',
           '8192 MB',
           '1200 GB',
           '2000 GB',
           'oradb-prod-02:1521/CDBPROD',
           'CDB',
           3 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-prod-03',
           'DWCDB1',
           '19.22.0.0.0',
           'DWCDB',
           'ARCHIVELOG',
           'PRIMARY',
           'DWCDB',
           'AL32UTF8',
           'Enterprise Edition',
           'NO',
           '65536 MB',
           '16384 MB',
           '2400 GB',
           '4000 GB',
           'oradb-prod-03:1521/DWCDB',
           'CDB',
           2 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-exacc-01',
           'EXADB1',
           '19.22.0.0.0',
           'EXADB',
           'ARCHIVELOG',
           'PRIMARY',
           'EXADB',
           'AL32UTF8',
           'Enterprise Edition',
           'YES',
           '131072 MB',
           '32768 MB',
           '5000 GB',
           '20000 GB',
           'oradb-exacc-01:1521/EXADB',
           'CDB',
           5 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-exacc-02',
           'EXADB2',
           '19.22.0.0.0',
           'EXADB',
           'ARCHIVELOG',
           'PRIMARY',
           'EXADB',
           'AL32UTF8',
           'Enterprise Edition',
           'YES',
           '131072 MB',
           '32768 MB',
           '5000 GB',
           '20000 GB',
           'oradb-exacc-02:1521/EXADB',
           'CDB',
           5 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PROD',
           'Standard Edition 2',
           'oradb-se2-prod-01',
           'ORCL',
           '19.3.0.0.0',
           'ORCL',
           'ARCHIVELOG',
           'PRIMARY',
           'ORCL',
           'AL32UTF8',
           'Standard Edition 2',
           'NO',
           '8192 MB',
           '2048 MB',
           null,
           null,
           'oradb-se2-prod-01:1521/ORCL',
           'NON-CDB',
           0 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PROD',
           'Standard Edition 2',
           'oradb-se2-prod-02',
           'APPDB',
           '19.3.0.0.0',
           'APPDB',
           'ARCHIVELOG',
           'PRIMARY',
           'APPDB',
           'AL32UTF8',
           'Standard Edition 2',
           'NO',
           '8192 MB',
           '2048 MB',
           null,
           null,
           'oradb-se2-prod-02:1521/APPDB',
           'NON-CDB',
           0 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-aix-01',
           'LEGCDB1',
           '12.2.0.1.0',
           'LEGCDB',
           'ARCHIVELOG',
           'PRIMARY',
           'LEGCDB',
           'WE8ISO8859P1',
           'Enterprise Edition',
           'NO',
           '16384 MB',
           '4096 MB',
           '800 GB',
           '1500 GB',
           'oradb-aix-01:1521/LEGCDB',
           'CDB',
           2 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PROD',
           'Enterprise Edition',
           'oradb-aix-02',
           'LEGCDB1',
           '12.2.0.1.0',
           'LEGCDB',
           'ARCHIVELOG',
           'PHYSICAL STANDBY',
           'LEGCDB_STB',
           'WE8ISO8859P1',
           'Enterprise Edition',
           'NO',
           '16384 MB',
           '4096 MB',
           '800 GB',
           '1500 GB',
           'oradb-aix-02:1521/LEGCDB_STB',
           'CDB',
           0 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'UAT',
           'Enterprise Edition',
           'oradb-uat-01',
           'CDBUAT1',
           '19.22.0.0.0',
           'CDBUAT',
           'ARCHIVELOG',
           'PRIMARY',
           'CDBUAT',
           'AL32UTF8',
           'Enterprise Edition',
           'NO',
           '16384 MB',
           '4096 MB',
           '600 GB',
           '1000 GB',
           'oradb-uat-01:1521/CDBUAT',
           'CDB',
           3 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'UAT',
           'Enterprise Edition',
           'oradb-uat-02',
           'UTDB',
           '19.3.0.0.0',
           'UTDB',
           'ARCHIVELOG',
           'PRIMARY',
           'UTDB',
           'AL32UTF8',
           'Enterprise Edition',
           'NO',
           '8192 MB',
           '2048 MB',
           '400 GB',
           '800 GB',
           'oradb-uat-02:1521/UTDB',
           'NON-CDB',
           0 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'UAT',
           'Standard Edition 2',
           'oradb-se2-uat-01',
           'ORCUAT',
           '19.3.0.0.0',
           'ORCUAT',
           'NOARCHIVELOG',
           'PRIMARY',
           'ORCUAT',
           'AL32UTF8',
           'Standard Edition 2',
           'NO',
           '4096 MB',
           '1024 MB',
           null,
           null,
           'oradb-se2-uat-01:1521/ORCUAT',
           'NON-CDB',
           0 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'DEV',
           'Enterprise Edition',
           'oradb-dev-01',
           'CDBDEV1',
           '21.3.0.0.0',
           'CDBDEV',
           'ARCHIVELOG',
           'PRIMARY',
           'CDBDEV',
           'AL32UTF8',
           'Enterprise Edition',
           'NO',
           '8192 MB',
           '2048 MB',
           '300 GB',
           '600 GB',
           'oradb-dev-01:1521/CDBDEV',
           'CDB',
           2 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'DEV',
           'Enterprise Edition',
           'oradb-dev-02',
           'DEVDB',
           '19.3.0.0.0',
           'DEVDB',
           'ARCHIVELOG',
           'PRIMARY',
           'DEVDB',
           'AL32UTF8',
           'Enterprise Edition',
           'NO',
           '8192 MB',
           '2048 MB',
           '200 GB',
           '400 GB',
           'oradb-dev-02:1521/DEVDB',
           'NON-CDB',
           0 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'DEV',
           'Standard Edition 2',
           'oradb-se2-dev-01',
           'DEVSEA',
           '19.3.0.0.0',
           'DEVSEA',
           'NOARCHIVELOG',
           'PRIMARY',
           'DEVSEA',
           'AL32UTF8',
           'Standard Edition 2',
           'NO',
           '4096 MB',
           '512 MB',
           null,
           null,
           'oradb-se2-dev-01:1521/DEVSEA',
           'NON-CDB',
           0 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'DEV',
           'Standard Edition 2',
           'oradb-se2-dev-02',
           'DEVSEB',
           '19.3.0.0.0',
           'DEVSEB',
           'NOARCHIVELOG',
           'PRIMARY',
           'DEVSEB',
           'AL32UTF8',
           'Standard Edition 2',
           'NO',
           '2048 MB',
           '512 MB',
           null,
           null,
           'oradb-se2-dev-02:1521/DEVSEB',
           'NON-CDB',
           0 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'QA',
           'Enterprise Edition',
           'oradb-qa-01',
           'CDBQA1',
           '19.22.0.0.0',
           'CDBQA',
           'ARCHIVELOG',
           'PRIMARY',
           'CDBQA',
           'AL32UTF8',
           'Enterprise Edition',
           'NO',
           '8192 MB',
           '2048 MB',
           '300 GB',
           '600 GB',
           'oradb-qa-01:1521/CDBQA',
           'CDB',
           2 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'QA',
           'Standard Edition 2',
           'oradb-se2-qa-01',
           'QASE2',
           '19.3.0.0.0',
           'QASE2',
           'NOARCHIVELOG',
           'PRIMARY',
           'QASE2',
           'AL32UTF8',
           'Standard Edition 2',
           'NO',
           '4096 MB',
           '1024 MB',
           null,
           null,
           'oradb-se2-qa-01:1521/QASE2',
           'NON-CDB',
           0 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PREPROD',
           'Enterprise Edition',
           'oradb-pprod-01',
           'CDBPPRD1',
           '19.22.0.0.0',
           'CDBPPRD',
           'ARCHIVELOG',
           'PRIMARY',
           'CDBPPRD',
           'AL32UTF8',
           'Enterprise Edition',
           'NO',
           '16384 MB',
           '4096 MB',
           '800 GB',
           '1500 GB',
           'oradb-pprod-01:1521/CDBPPRD',
           'CDB',
           3 );
insert into oracle_databases (
   environment,
   license_type,
   hostname,
   instance_name,
   db_version,
   db_name,
   db_log_mode,
   db_role,
   db_unique_name,
   db_charset,
   db_edition,
   rac_state,
   sga,
   pga,
   asm_free,
   asm_total,
   easy_connect_tns,
   database_type,
   count_pdb
) values ( 'PREPROD',
           'Enterprise Edition',
           'oradb-pprod-02',
           'CDBPPRD1',
           '19.22.0.0.0',
           'CDBPPRD',
           'ARCHIVELOG',
           'PHYSICAL STANDBY',
           'CDBPPRD_STB',
           'AL32UTF8',
           'Enterprise Edition',
           'NO',
           '16384 MB',
           '4096 MB',
           '800 GB',
           '1500 GB',
           'oradb-pprod-02:1521/CDBPPRD_STB',
           'CDB',
           0 );

-- ============================================================
-- mssql_databases
-- ============================================================
-- SQLPROD01
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD01',
           5,
           'ERP_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:15:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2019-03-15 10:23:44.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD01',
           6,
           'CRM_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:30:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2019-06-01 14:15:22.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
-- SQLPROD02
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD02',
           5,
           'FINANCE_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:20:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2019-03-15 10:25:10.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD02',
           6,
           'HRDB_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:45:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2020-01-10 08:05:33.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
-- SQLPROD03
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD03',
           5,
           'DWH_PROD',
           'ONLINE',
           'BULK_LOGGED',
           '160',
           'French_CI_AS',
           '2026-06-22 01:00:00.000',
           '2026-06-29 01:00:00.000',
           null,
           '2023-06-01 09:10:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD03',
           6,
           'REPORTING_PROD',
           'ONLINE',
           'SIMPLE',
           '160',
           'French_CI_AS',
           '2026-06-29 01:30:00.000',
           null,
           null,
           '2023-06-01 09:15:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
-- SQLPROD04
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD04',
           5,
           'BILLING_PROD',
           'ONLINE',
           'FULL',
           '160',
           'French_CI_AS',
           '2026-06-29 00:10:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2023-06-01 10:00:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD04',
           6,
           'PORTAL_PROD',
           'ONLINE',
           'FULL',
           '160',
           'French_CI_AS',
           '2026-06-29 00:20:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2023-07-15 11:30:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
-- SQLPROD05
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD05',
           5,
           'LOGISTICS_PROD',
           'ONLINE',
           'FULL',
           '140',
           'SQL_Latin1_General_CP1_CI_AS',
           '2026-06-29 00:05:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:30:00.000',
           '2017-08-20 08:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'PROD' );
-- SQLPROD06
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD06',
           5,
           'INTEGRATION_PROD',
           'ONLINE',
           'FULL',
           '160',
           'French_CI_AS',
           '2026-06-29 00:15:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2024-09-01 09:00:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD06',
           6,
           'DOCMGT_PROD',
           'ONLINE',
           'FULL',
           '160',
           'French_CI_AS',
           '2026-06-29 00:30:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2024-09-01 09:30:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
-- SQLPROD07
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD07',
           5,
           'ANALYTICS_PROD',
           'ONLINE',
           'BULK_LOGGED',
           '160',
           'French_CI_AS',
           '2026-06-22 02:00:00.000',
           '2026-06-29 02:00:00.000',
           null,
           '2024-10-01 10:00:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD07',
           6,
           'ARCHIVING_PROD',
           'ONLINE',
           'SIMPLE',
           '160',
           'French_CI_AS',
           '2026-06-29 02:30:00.000',
           null,
           null,
           '2024-10-01 10:30:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
-- SQLPROD08
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD08',
           5,
           'INTRANET_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 01:00:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:00:00.000',
           '2022-01-01 08:00:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
-- SQLPROD09
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPROD09',
           5,
           'QUALITY_PROD',
           'ONLINE',
           'FULL',
           '160',
           'Latin1_General_CI_AS',
           '2026-06-29 01:15:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:15:00.000',
           '2024-11-15 09:00:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PROD' );
-- SQLCLU01
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLCLU01',
           5,
           'WORKFLOW_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:15:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2020-09-10 10:00:00.000',
           0,
           'CORP\sqlsvc_clu',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLCLU01',
           6,
           'BPMDB_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:30:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2020-09-10 10:30:00.000',
           0,
           'CORP\sqlsvc_clu',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLCLU01',
           7,
           'TASKMGR_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:45:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2021-03-01 11:00:00.000',
           0,
           'CORP\sqlsvc_clu',
           null,
           null,
           'PROD' );
-- SQLCLU02
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLCLU02',
           5,
           'SALESDB_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:15:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2020-09-10 12:00:00.000',
           0,
           'CORP\sqlsvc_clu',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLCLU02',
           6,
           'MKTGDB_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:30:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2020-09-10 12:30:00.000',
           0,
           'CORP\sqlsvc_clu',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLCLU02',
           7,
           'LEADTRK_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:45:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2021-06-15 09:00:00.000',
           0,
           'CORP\sqlsvc_clu',
           null,
           null,
           'PROD' );
-- SQLCLU03
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLCLU03',
           5,
           'DATAMART_PROD',
           'ONLINE',
           'BULK_LOGGED',
           '160',
           'Latin1_General_CI_AS',
           '2026-06-22 03:00:00.000',
           '2026-06-29 03:00:00.000',
           null,
           '2023-11-15 10:00:00.000',
           0,
           'CORP\sqlsvc_clu',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLCLU03',
           6,
           'OLAP_PROD',
           'ONLINE',
           'SIMPLE',
           '160',
           'Latin1_General_CI_AS',
           '2026-06-29 03:30:00.000',
           null,
           null,
           '2023-11-15 10:30:00.000',
           0,
           'CORP\sqlsvc_clu',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLCLU03',
           7,
           'RISKDB_PROD',
           'ONLINE',
           'FULL',
           '160',
           'Latin1_General_CI_AS',
           '2026-06-29 00:15:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2023-12-01 09:00:00.000',
           0,
           'CORP\sqlsvc_clu',
           null,
           null,
           'PROD' );
-- SQLSTD01
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLSTD01',
           5,
           'CMSDB_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 01:00:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:00:00.000',
           '2021-03-03 09:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'PROD' );
-- SQLSTD02
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLSTD02',
           5,
           'TICKETING_PROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 01:00:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:00:00.000',
           '2021-03-03 10:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'PROD' );
-- SQLSTD03
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLSTD03',
           5,
           'ASSETMGMT_PROD',
           'ONLINE',
           'FULL',
           '140',
           'French_CI_AS',
           '2026-06-29 01:00:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:00:00.000',
           '2018-06-15 08:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'PROD' );
-- SQLSTD04
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLSTD04',
           5,
           'CONFMGMT_PROD',
           'ONLINE',
           'FULL',
           '160',
           'Latin1_General_CI_AS',
           '2026-06-29 01:00:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:00:00.000',
           '2024-01-01 09:00:00.000',
           0,
           'CORP\sqlsvc_std',
           null,
           null,
           'PROD' );
-- SQLSTD05
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLSTD05',
           5,
           'STOCKDB_PROD',
           'ONLINE',
           'FULL',
           '160',
           'Latin1_General_CI_AS',
           '2026-06-29 01:00:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:00:00.000',
           '2024-01-15 09:00:00.000',
           0,
           'CORP\sqlsvc_std',
           null,
           null,
           'PROD' );
-- SQLPPROD01
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPPROD01',
           5,
           'ERP_PPROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 01:00:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:00:00.000',
           '2019-10-10 09:00:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PREPROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPPROD01',
           6,
           'DWH_PPROD',
           'ONLINE',
           'SIMPLE',
           '150',
           'French_CI_AS',
           '2026-06-29 01:30:00.000',
           null,
           null,
           '2019-10-10 09:30:00.000',
           0,
           'CORP\sqlsvc_prod',
           null,
           null,
           'PREPROD' );
-- SQLPPROD02
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPPROD02',
           5,
           'CRM_PPROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 01:00:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:00:00.000',
           '2019-10-10 10:00:00.000',
           0,
           'CORP\sqlsvc_uat',
           null,
           null,
           'PREPROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLPPROD02',
           6,
           'FINANCE_PPROD',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 01:15:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:00:00.000',
           '2019-10-10 10:30:00.000',
           0,
           'CORP\sqlsvc_uat',
           null,
           null,
           'PREPROD' );
-- SQLUAT01
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLUAT01',
           5,
           'ERP_UAT',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 02:00:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2020-01-20 09:00:00.000',
           0,
           'CORP\sqlsvc_uat',
           null,
           null,
           'UAT' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLUAT01',
           6,
           'CRM_UAT',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 02:15:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2020-01-20 09:30:00.000',
           0,
           'CORP\sqlsvc_uat',
           null,
           null,
           'UAT' );
-- SQLUAT02
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLUAT02',
           5,
           'FINANCE_UAT',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 02:00:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2020-01-20 10:00:00.000',
           0,
           'CORP\sqlsvc_uat',
           null,
           null,
           'UAT' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLUAT02',
           6,
           'DWH_UAT',
           'ONLINE',
           'SIMPLE',
           '150',
           'French_CI_AS',
           '2026-06-29 02:30:00.000',
           null,
           null,
           '2020-01-20 10:30:00.000',
           0,
           'CORP\sqlsvc_uat',
           null,
           null,
           'UAT' );
-- SQLUAT03
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLUAT03',
           5,
           'HRDB_UAT',
           'ONLINE',
           'FULL',
           '160',
           'French_CI_AS',
           '2026-06-29 02:00:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2023-09-01 09:00:00.000',
           0,
           'CORP\sqlsvc_uat',
           null,
           null,
           'UAT' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLUAT03',
           6,
           'PORTAL_UAT',
           'ONLINE',
           'FULL',
           '160',
           'French_CI_AS',
           '2026-06-29 02:15:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2023-09-01 09:30:00.000',
           0,
           'CORP\sqlsvc_uat',
           null,
           null,
           'UAT' );
-- SQLUAT04
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLUAT04',
           5,
           'BILLING_UAT',
           'ONLINE',
           'FULL',
           '140',
           'SQL_Latin1_General_CP1_CI_AS',
           '2026-06-29 02:00:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2017-05-01 08:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'UAT' );
-- SQLUAT05
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLUAT05',
           5,
           'LOGISTICS_UAT',
           'ONLINE',
           'FULL',
           '160',
           'French_CI_AS',
           '2026-06-29 02:00:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2024-03-01 09:00:00.000',
           0,
           'CORP\sqlsvc_uat',
           null,
           null,
           'UAT' );
-- SQLDEV01
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLDEV01',
           5,
           'ERP_DEV',
           'ONLINE',
           'SIMPLE',
           '160',
           'French_CI_AS',
           '2026-06-22 03:00:00.000',
           null,
           null,
           '2023-02-15 09:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'DEV' );
-- SQLDEV02
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLDEV02',
           5,
           'CRM_DEV',
           'ONLINE',
           'SIMPLE',
           '160',
           'French_CI_AS',
           '2026-06-22 03:00:00.000',
           null,
           null,
           '2023-02-15 09:30:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'DEV' );
-- SQLDEV03
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLDEV03',
           5,
           'DWH_DEV',
           'ONLINE',
           'SIMPLE',
           '150',
           'French_CI_AS',
           null,
           null,
           null,
           '2021-07-01 10:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'DEV' );
-- SQLDEV04
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLDEV04',
           5,
           'FINANCE_DEV',
           'ONLINE',
           'SIMPLE',
           '150',
           'SQL_Latin1_General_CP1_CI_AS',
           null,
           null,
           null,
           '2022-04-01 09:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'DEV' );
-- SQLDEV05
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLDEV05',
           5,
           'HRDB_DEV',
           'ONLINE',
           'SIMPLE',
           '140',
           'French_CI_AS',
           null,
           null,
           null,
           '2018-01-01 09:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'DEV' );
-- SQLDEV06
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLDEV06',
           5,
           'PORTAL_DEV',
           'ONLINE',
           'SIMPLE',
           '160',
           'French_CI_AS',
           '2026-06-22 03:00:00.000',
           null,
           null,
           '2024-06-01 09:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'DEV' );
-- SQLQA01
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLQA01',
           5,
           'ERP_QA',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 03:00:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2020-05-01 09:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'QA' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLQA01',
           6,
           'CRM_QA',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 03:15:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2020-05-01 09:30:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'QA' );
-- SQLQA02
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLQA02',
           5,
           'FINANCE_QA',
           'ONLINE',
           'FULL',
           '160',
           'French_CI_AS',
           '2026-06-29 03:00:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2023-07-01 09:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'QA' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLQA02',
           6,
           'DWH_QA',
           'ONLINE',
           'SIMPLE',
           '160',
           'French_CI_AS',
           '2026-06-29 03:30:00.000',
           null,
           null,
           '2023-07-01 09:30:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'QA' );
-- SQLQA03
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLQA03',
           5,
           'HRDB_QA',
           'ONLINE',
           'FULL',
           '140',
           'SQL_Latin1_General_CP1_CI_AS',
           '2026-06-29 03:00:00.000',
           null,
           '2026-06-29 09:00:00.000',
           '2017-11-05 08:00:00.000',
           0,
           'NT Service\MSSQLSERVER',
           null,
           null,
           'QA' );
-- SQLAGPROD01 (PRIMARY)
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLAGPROD01',
           5,
           'APP_AG1',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:15:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2020-12-01 09:00:00.000',
           0,
           'CORP\sqlsvc_ag',
           'PRIMARY',
           'AG_PROD01',
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLAGPROD01',
           6,
           'CRM_AG1',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:30:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2020-12-01 09:30:00.000',
           0,
           'CORP\sqlsvc_ag',
           'PRIMARY',
           'AG_PROD01',
           'PROD' );
-- SQLAGPROD02 (SECONDARY)
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLAGPROD02',
           5,
           'APP_AG1',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           null,
           null,
           null,
           '2020-12-01 09:00:00.000',
           0,
           'CORP\sqlsvc_ag',
           'SECONDARY',
           'AG_PROD01',
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLAGPROD02',
           6,
           'CRM_AG1',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           null,
           null,
           null,
           '2020-12-01 09:30:00.000',
           0,
           'CORP\sqlsvc_ag',
           'SECONDARY',
           'AG_PROD01',
           'PROD' );
-- SQLAGPROD03 (PRIMARY)
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLAGPROD03',
           5,
           'REPORTING_AG',
           'ONLINE',
           'FULL',
           '160',
           'French_CI_AS',
           '2026-06-29 00:15:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2023-10-01 09:00:00.000',
           0,
           'CORP\sqlsvc_ag',
           'PRIMARY',
           'AG_PROD02',
           'PROD' );
-- SQLAGPROD04 (SECONDARY)
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLAGPROD04',
           5,
           'REPORTING_AG',
           'ONLINE',
           'FULL',
           '160',
           'French_CI_AS',
           null,
           null,
           null,
           '2023-10-01 09:00:00.000',
           0,
           'CORP\sqlsvc_ag',
           'SECONDARY',
           'AG_PROD02',
           'PROD' );
-- SQLREP01
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLREP01',
           5,
           'ERP_REP',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:15:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2021-10-01 09:00:00.000',
           0,
           'CORP\sqlsvc_rep',
           null,
           null,
           'PROD' );
insert into mssql_databases (
   hostname,
   database_id,
   database_name,
   database_state,
   recovery_model,
   compatibility_level,
   collation,
   last_backup_date,
   last_backup_diff_date,
   last_backup_log_date,
   create_date,
   is_mirroring_enabled,
   owner,
   agtype,
   agname,
   env
) values ( 'SQLREP01',
           6,
           'CRM_REP',
           'ONLINE',
           'FULL',
           '150',
           'French_CI_AS',
           '2026-06-29 00:30:00.000',
           '2026-06-29 08:00:00.000',
           '2026-06-29 09:45:00.000',
           '2021-10-01 09:30:00.000',
           0,
           'CORP\sqlsvc_rep',
           null,
           null,
           'PROD' );

commit;