#!/bin/bash
echo "truncate table mssql_security_auditlevel;
      truncate table mssql_security_configoptions;
      truncate table mssql_security_dbproperties;
      truncate table mssql_security_encryption;
      truncate table mssql_security_groups;
      truncate table mssql_security_guestconnect;
      truncate table mssql_security_logins;
      truncate table mssql_security_orphanedusers;
      truncate table mssql_security_publicpermission;
      truncate table mssql_security_registryinfo;
      truncate table mssql_security_sqlserveraudit;" | mariadb -u root -************************************* inventory

IFS=,

###LOAD mssql_security_configoptions
while read servername name config_value run_value
      do
        echo "INSERT INTO mssql_security_configoptions (servername,name,config_value,run_value) VALUES ('$servername','$name','$config_value','$run_value');"
done <  lists/mssql_security_configoptions.lst| mariadb -u root -************************************* inventory;

###LOAD mssql_security_registryinfo
while read servername name value 
      do
        echo "INSERT INTO mssql_security_registryinfo (servername,name,value) VALUES ('$servername','$name','$value');"
done <  lists/mssql_security_registryinfo.lst| mariadb -u root -************************************* inventory;

###LOAD mssql_security_guestconnect
while read servername db_name permission_name state_desc
      do
        echo "INSERT INTO mssql_security_guestconnect (servername,db_name,permission_name,state_desc) VALUES ('$servername','$db_name','$permission_name','$state_desc');"
done <  lists/mssql_security_guestconnect.lst| mariadb -u root -************************************* inventory;

###LOAD mssql_security_orphanedusers
while read servername db_name user_name
      do
        echo "INSERT INTO mssql_security_orphanedusers (servername,db_name,user_name) VALUES ('$servername','$db_name','$user_name');"
done <  lists/mssql_security_orphanedusers.lst| mariadb -u root -************************************* inventory;

###LOAD mssql_security_dbproperties
while read servername db_name is_auto_close_on is_trustworthy_on
      do
        echo "INSERT INTO mssql_security_dbproperties (servername,db_name,is_auto_close_on,is_trustworthy_on) VALUES ('$servername','$db_name','$is_auto_close_on','$is_trustworthy_on');"
done <  lists/mssql_security_dbproperties.lst| mariadb -u root -************************************* inventory;

###LOAD mssql_security_publicperm
while read servername db_name username permission_name state_desc 
      do
        echo "INSERT INTO mssql_security_publicpermission (servername,db_name,username,permission_name,state_desc) VALUES ('$servername','$db_name','$username','$permission_name','$state_desc');"
done <  lists/mssql_security_publicperm.lst| mariadb -u root -************************************* inventory;

###LOAD mssql_security_groups
while read servername localgroupname permission_name state_desc 
      do
        echo "INSERT INTO mssql_security_groups (servername,localgroupname,permission_name,state_desc) VALUES ('$servername','$localgroupname','$permission_name','$state_desc');"
done <  lists/mssql_security_groups.lst| mariadb -u root -************************************* inventory;

###LOAD mssql_security_logins
while read servername login_name principal_id is_sysadmin is_policy_checked access_method is_expiration_checked is_disabled create_date
      do
        echo "INSERT INTO mssql_security_logins (servername,login_name,principal_id,is_sysadmin,is_policy_checked,access_method,is_expiration_checked,is_disabled,create_date) VALUES ('$servername','$login_name','$principal_id','$is_sysadmin','$is_policy_checked','$access_method','$is_expiration_checked','$is_disabled','$create_date');"
done <  lists/mssql_security_logins.lst| mariadb -u root -************************************* inventory;

###LOAD mssql_security_auditlevel
while read servername auditlevel
      do
        echo "INSERT INTO mssql_security_auditlevel (servername,auditlevel) VALUES ('$servername','$auditlevel');"
done <  lists/mssql_security_auditlevel.lst| mariadb -u root -************************************* inventory;


###LOAD mssql_security_sqlserveraudit
while read servername auditname auditenabled writelocation auditspecificationname auditspecificationenabled auditactionname audited_result
      do
        echo "INSERT INTO mssql_security_sqlserveraudit (servername,auditname,auditenabled,writelocation,auditspecificationname,auditspecificationenabled,auditactionname,audited_result) VALUES ('$servername','$auditname','$auditenabled','$writelocation','$auditspecificationname','$auditspecificationenabled','$auditactionname','$audited_result');"
done <  lists/mssql_security_sqlserveraudit.lst| mariadb -u root -************************************* inventory;

###LOAD mssql_security_encryption
while read servername db_name key_type key_name algorithm_desc 
      do
        echo "INSERT INTO mssql_security_encryption (servername,db_name,key_type,key_name,algorithm_desc) VALUES ('$servername','$db_name','$key_type','$key_name','$algorithm_desc');"
done <  lists/mssql_security_encryption.lst| mariadb -u root -************************************* inventory;


##BACKUP ALL LISTS
export DIR_TIME=`date '+%y%m%d%H%M%S'`
mkdir -p lists/${DIR_TIME}
cp lists/mssql*.lst lists/${DIR_TIME}/

